<?php

/**
* @file
* Provides IIT custom tokens
*/


/* ***************************************** */
/* Hook Implementations                      */
/* ***************************************** */

/**
 * Implements hook_token_info(). This hook will register the tokens.
 */
function iit_tokens_token_info() {
  $info['tokens']['array']['join-path-noroot-alias'] = array(
    'name' => t('Joined Path No Root'),
    'description' => t('The array values minus the root element cleaned by Pathauto and then joined with the slash into a string that resembles an URL.'),
  );

  $info['tokens']['random']['short-hash'] = array(
    'name' => t('Short Hash'),
    'description' => t('A base64 URL safe sha256 encoding of the current time. Only the first 8 base64 characters is returned.'),
  );

  return $info;
}

/**
 * Implements hook_tokens(). This hook will operate the token and replace it with it's value.
 *
 * @param $type
 *   The machine-readable name of the type (group) of token being replaced, such
 *   as 'node', 'user', or another type defined by a hook_token_info()
 *   implementation.
 * @param $tokens
 *   An array of tokens to be replaced. The keys are the machine-readable token
 *   names, and the values are the raw [type:token] strings that appeared in the
 *   original text.
 * @param array $data
 *   (optional) An associative array of data objects to be used when generating
 *   replacement values, as supplied in the $data parameter to token_replace().
 * @param array $options
 *   (optional) An associative array of options for token replacement; see
 *   token_replace() for possible values.
 *
 * @return array An associative array of replacement values, keyed by the raw [type:token]
 * An associative array of replacement values, keyed by the raw [type:token]
 * strings from the original text.
 */
function iit_tokens_tokens($type, $tokens, array $data = array(), array $options = array()) {
    $replacements = array();

    if ($type == 'array' && !empty($data['array'])) {
      $array = $data['array'];
      foreach ($tokens as $name => $original) {
        switch ($name) {
          case 'join-path-noroot-alias':
            module_load_include('inc', 'pathauto');
            $values = array();
            foreach (element_children($array) as $key) {
              $value = is_array($array[$key]) ? render($array[$key]) : (string) $array[$key];
              $value = pathauto_cleanstring($value);
              $values[] = $value;
            }
            $values_noroot = $values;
            array_shift($values_noroot);
            if (count($values_noroot) > 0) {
              $replacements[$original] = implode('/', $values_noroot);
            }
            break;
        }
      }
    }

    // Random tokens.
    if ($type == 'random') {
      foreach ($tokens as $name => $original) {
        switch ($name) {
          case 'short-hash':
            $date = new DateTime();
            $hash = drupal_hash_base64($date->format('l, d-F-Y H:i:s T'));
            $replacements[$original] = substr($hash, 0, 8);
            break;
        }
      }
    }

    return $replacements;
}